### ISSUE TITLE
Add storage tests to Github Actions

### ISSUE THREAD

**Issue by iesahin** [iesahin/xvc#5]
Remote tests use feature flags to prevent to run every time the test suite runs. 

These test could be run manually, either by per remote or in total. 

- [ ] Enter all relevant credentials as secrets to Github Actions
- [ ] Create a new CI file that has separate testing for each of the remotes, via matrix

**Comment by iesahin** [comment]
This may be a duplicate of #18

**Comment by iesahin** [comment]
For coverage reports to be sensible, all storage tests must be completed. Instead of separating storage types from the main test suite, maybe coverage check should be activated manually. There will be two kinds of tests. (1) for PRs, quickly assessing the test. If there are *_storage_* files, run the respective test. (2) for releases and manually, get a coverage report by running all possible tests.

**Comment by iesahin** [comment]
I think, until I see the effects on my credit card, I'm overreacting about the cloud bills. I'll just add measures to prevent PRs from others to run these tests and coverage. 

GA jobs has conditions:

```yaml

name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
```

There is also `actor` and `triggering_actor` fields in `github` context. 

> github.actor | string | The username of the user that triggered the initial workflow run. If the workflow run is a re-run, this value may differ from github.triggering_actor. Any workflow re-runs will use the privileges of github.actor, even if the actor initiating the re-run (github.triggering_actor) has different privileges.

Now, I can run a test with `--all-features` if the `github.actor` is me. Otherwise, only non-cloud tests will be run and no coverage report will be collected. If I need coverage report for someone else, I can manually trigger the test.
